### ISSUE TITLE
Encryption segfault

### ISSUE THREAD

**Issue by azmeuk** [mehcode/python-xmlsec#121] opened 2020-04-03 10:55 UTC
I used the example to try to encrypt a XML file. I am probably doing it wrong, however this code produce a segfault instead of a python exception, so I though it worth reporting it:

```python
import lxml
import xmlsec

content = """<?xml version="1.0"?>
<Foobar>
    <Foo>Hello world</Foo>
    <Bar></Bar>
</Foobar>"""

pubkey = """-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDe+hkicNP7ROHUssGNtHwiT2Ew
HFrSk/qwrcq8v5metRtTTFPE/nmzSkRnTs3GMpi57rBdxBBJW5W9cpNyGUh0jNXc
VrOSClpD5Ri2hER/GcNrxVRP7RlWOqB1C03q4QYmwjHZ+zlM4OUhCCAtSWflB4wC
Ka1g88CjFwRw/PB9kwIDAQAB
-----END PUBLIC KEY-----"""

template = lxml.etree.fromstring(content)
data = template.getchildren()[0]

manager = xmlsec.KeysManager()
manager.add_key(xmlsec.Key.from_memory(pubkey, xmlsec.constants.KeyDataFormatPem, None))

enc_data = xmlsec.template.encrypted_data_create(template, xmlsec.constants.TransformAes128Cbc, type=xmlsec.constants.TypeEncContent, ns="xenc")
xmlsec.template.encrypted_data_ensure_cipher_value(enc_data)
key_info = xmlsec.template.encrypted_data_ensure_key_info(enc_data, ns="dsig")

enc_ctx = xmlsec.EncryptionContext(manager)
enc_ctx.key = xmlsec.Key.generate(xmlsec.constants.KeyDataAes, 128, xmlsec.constants.KeyDataTypeSession)

enc_data = enc_ctx.encrypt_xml(enc_data, data)
```

It segfaults with python 3.8 and 2.7 with python-xmlsec 1.3.3

**Comment by hoefling** [comment] 2020-05-04 18:24
Use `type=xmlsec.constants.TypeEncElement` instead of `type=xmlsec.constants.TypeEncContent`. As for the segfault, it is fixed on current master (but wasn't released properly). Try installing from master branch.

**Comment by hoefling** [comment] 2020-05-21 14:48
@azmeuk the issue is not reproducible with the latest 1.3.8 anymore, thus closing. Also the docs are updated. Ping me if this should be reopened though!

**Closed by hoefling** 2020-05-21 14:48 UTC
