### ISSUE TITLE
Package setup.py egg_info requires an external resource

### ISSUE THREAD

**Issue by iepathos** [mehcode/python-xmlsec#102] opened 2019-03-29 19:54 UTC
This pip package tries for an external resource during setup.py egg_info which is called at the start of installation.  This breaks typical pip package installation which should respect defined pip registries and only use those for installation.  This breaks installation for anyone trying to install this in an offline environment from a pip mirror or from a clone of this repository.  This package should include w/e egg_info it's trying to find from non-pip registry sources in the releases.

**Comment by hoefling** [comment] 2020-05-21 15:20
@iepathos can you confirm the issue with the latest 1.3.8 release?

**Comment by hoefling** [comment] 2020-06-04 13:53
Closed as cannot reproduce this. Feel free to ping me if the issue should be reopened, though.

**Closed by hoefling** 2020-06-04 13:53 UTC
Labels: awaiting-response

**Comment by iepathos** [comment] 2021-05-18 20:12
This is fixed in latest release thanks!
