### ISSUE TITLE
Fails to install using pip - "lxml-version.h: No such file or directory"

### ISSUE THREAD

**Issue by nijel** [mehcode/python-xmlsec#200] opened 2021-12-13 11:33 UTC
This is a similar error as in #198, but not related to `lxml==4.7.0`, so I'm opening a separate issue for it.

For me, the builds started to fail this morning while having lxml version pinned to 4.6.4 (we do pin nearly everything).

* [Working build](https://github.com/WeblateOrg/docker/runs/4500454180?check_suite_focus=true) 11 hours ago
* [Broken build](https://github.com/WeblateOrg/docker/runs/4504428407?check_suite_focus=true#step:6:2191) 1 hour ago

There are no code changes between and the only difference in the installed packages is `amqp==5.0.7` instead of `amqp==5.0.6` (this one is not pinned because we don't use it directly, but it's installed by Celery).

When playing with it a bit more, these seems to be something broken in the pip build. In the xmlsec sources `python ./setup.py bdist_wheel` works file, while `pip install .` fails:

```
$ pip install .
Processing /tmp/xmlsec-1.3.12
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: lxml>=3.8 in /tmp/.venv/lib/python3.9/site-packages (from xmlsec==1.3.12) (4.6.5)
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/.venv/bin/python /tmp/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpw9sqs_at
       cwd: /tmp/xmlsec-1.3.12
  Complete output (26 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'src/xmlsec/__init__.py' not found (or not a regular file)
  creating build
  creating build/lib.linux-x86_64-3.9
  creating build/lib.linux-x86_64-3.9/xmlsec
  copying src/xmlsec/py.typed -> build/lib.linux-x86_64-3.9/xmlsec
  copying src/xmlsec/constants.pyi -> build/lib.linux-x86_64-3.9/xmlsec
  copying src/xmlsec/__init__.pyi -> build/lib.linux-x86_64-3.9/xmlsec
  copying src/xmlsec/tree.pyi -> build/lib.linux-x86_64-3.9/xmlsec
  copying src/xmlsec/template.pyi -> build/lib.linux-x86_64-3.9/xmlsec
  running build_ext
  building 'xmlsec' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/tmp
  creating build/temp.linux-x86_64-3.9/tmp/xmlsec-1.3.12
  creating build/temp.linux-x86_64-3.9/tmp/xmlsec-1.3.12/src
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.12 -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml/includes -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml/includes/libxslt -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml/includes/libexslt -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml/includes/libxml -I/tmp/.venv/include -I/usr/include/python3.9 -c /tmp/xmlsec-1.3.12/src/constants.c -o build/temp.linux-x86_64-3.9/tmp/xmlsec-1.3.12/src/constants.o -g -std=c99 -fPIC -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.12 -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml/includes -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml/includes/libxslt -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml/includes/libexslt -I/tmp/pip-build-env-g9fgz395/normal/lib/python3.9/site-packages/lxml/includes/libxml -I/tmp/.venv/include -I/usr/include/python3.9 -c /tmp/xmlsec-1.3.12/src/ds.c -o build/temp.linux-x86_64-3.9/tmp/xmlsec-1.3.12/src/ds.o -g -std=c99 -fPIC -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
  In file included from /tmp/xmlsec-1.3.12/src/ds.c:15:
  /tmp/xmlsec-1.3.12/src/lxml.h:18:10: fatal error: lxml-version.h: Adresář nebo soubor neexistuje
     18 | #include <lxml-version.h>
        |          ^~~~~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for xmlsec
Failed to build xmlsec
ERROR: Could not build wheels for xmlsec, which is required to install pyproject.toml-based projects
```

I've also verified that `site-packages/lxml/includes/lxml-version.h` is present.

**Comment by hoefling** [comment] 2021-12-13 11:49
@nijel this may be related to build isolation, so the `lxml` installation is not used for building. Try `pip install --no-build-isolation .`, does it resolve it? If yes, it's a dupe of #198.

**Comment by regisb** [comment] 2021-12-13 12:04
I can confirm that this issue is related to build isolation. During setup, lxml==4.7.0 was being installed because xmlsec has `setup_requires=[..., 'lxml>=3.8']`.

**Comment by nijel** [comment] 2021-12-13 12:53
Ah, that could explain it. It works without isolation (after installing pkgconfig):


<details>

```
$ pip install --no-build-isolation .
Processing /tmp/xmlsec-1.3.12
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: lxml>=3.8 in /tmp/.venv/lib/python3.9/site-packages (from xmlsec==1.3.12) (4.6.5)
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /tmp/.venv/bin/python /tmp/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp7hyjw4x1
       cwd: /tmp/xmlsec-1.3.12
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'src/xmlsec/__init__.py' not found (or not a regular file)
  running build_ext
  Traceback (most recent call last):
    File "/tmp/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/tmp/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/.venv/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 400, in <module>
      setup(
    File "/tmp/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/.venv/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 45, in run
      import pkgconfig
  ModuleNotFoundError: No module named 'pkgconfig'
  ----------------------------------------
  ERROR: Failed building wheel for xmlsec
Failed to build xmlsec
ERROR: Could not build wheels for xmlsec, which is required to install pyproject.toml-based projects
$ pip install pkgconfig
Collecting pkgconfig
  Using cached pkgconfig-1.5.5-py3-none-any.whl (6.7 kB)
Installing collected packages: pkgconfig
Successfully installed pkgconfig-1.5.5
$ pip install --no-build-isolation .
Processing /tmp/xmlsec-1.3.12
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: lxml>=3.8 in /tmp/.venv/lib/python3.9/site-packages (from xmlsec==1.3.12) (4.6.5)
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (pyproject.toml) ... done
  Created wheel for xmlsec: filename=xmlsec-1.3.12-cp39-cp39-linux_x86_64.whl size=152195 sha256=e81e973c8e74d0daa69bf062bafe93f9e8e02c51017ca770a4413352d5b2bc59
  Stored in directory: /home/nijel/.cache/pip/wheels/50/34/39/5d7943b98340d3f270c17c5ee9181358b1bd8347f3325595b2
Successfully built xmlsec
Installing collected packages: xmlsec
  Attempting uninstall: xmlsec
    Found existing installation: xmlsec 1.3.12
    Uninstalling xmlsec-1.3.12:
      Successfully uninstalled xmlsec-1.3.12
Successfully installed xmlsec-1.3.12

```
</details>

That opens up another question - won't that cause issues if xmlsec is built against a different lxml version than is used in the runtime? Or to ask differently - is build isolation really desired in this case?

**Comment by hoefling** [comment] 2021-12-14 08:39
I guess this is best to be answered by `pip` maintainers - if a package is required both as build and runtime dependency, the dependency resolver should take it into account and use the resolved version for both stages.

**Comment by nijel** [comment] 2021-12-14 09:49
Allowing different versions is actually the reason for build isolation, so it IMHO works as intended.

**Comment by bmwant** [comment] 2021-12-15 11:47
are there any plans of releasing a new version with the fix included https://github.com/mehcode/python-xmlsec/commit/cf38b52c81d80897500f153ae5b9307439d6145a soon?

**Comment by hoefling** [comment] 2021-12-15 12:31
@bmwant `lxml==4.7.0` is now yanked, so it shouldn't be an issue anyway. If you are still hitting this, try cleaning your `pip` cache and retry.

**Comment by hoefling** [comment] 2021-12-15 12:55
@nijel again, IMO this isn't something that the package itself should be responsible for. Surely, you *may* get issues if you are building against `lxml==X` and executing against `lxml==Y` and `X` and `Y` are not ABI compatible. However, IMO this version discrepancy should be caught by the build backend, with either stopping the installation or issuing a warning about differences between build and runtime.
The only option I see to mitigate this on the package configuration side is a strict pin of `lxml` in both build and runtime deps, which won't help anyone either. I can also compare `lxml` versions at runtime and raise an error, just as it is done with `xmlsec1` already. The check only makes sense for `xmlsec1` though because its installation is not handled by `pip`, so it's fine. For `lxml`, it feels like doing the work which a build backend should do for me, even if PEP 517 doesn't explicitly state anything about it.

**Comment by nijel** [comment] 2021-12-15 13:43
Okay, I've created https://github.com/pypa/pip/issues/10731 to discuss this at pip. I don't see a good solution there and avoiding build isolation might be the least bad solution...

**Closed** 2022-08-20 21:30 UTC
