### ISSUE TITLE
Cannot install xmlsec in Windows 10

### ISSUE THREAD

**Issue by JoelKThomas** [mehcode/python-xmlsec#101] opened 2019-02-22 15:15 UTC
I am having Windows 10 and when i try to install xmlsec 
`pip install xmlsec==1.3.3`

I am getting an error like this

> Collecting xmlsec==1.3.3
>   Using cached https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz
> Requirement already satisfied: pkgconfig in *\testp\lib\site-packages (from xmlsec==1.3.3) (1.4.0)
> Requirement already satisfied: lxml>=3.0 in *\testp\lib\site-packages (from xmlsec==1.3.3) (4.3.1)
> Installing collected packages: xmlsec
>   Running setup.py install for xmlsec ... error
>     Complete output from command *\testp\scripts\python.exe -u -c "import setuptools, tokenize;__file__='*\AppData\\Local\\Temp\\pip-install-jnchsc4g\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record *\AppData\Local\Temp\pip-record-v7t_rx_3\install-record.txt --single-version-externally-managed --compile --install-headers *\testp\include\site\python3.7\xmlsec:
>     running install
>     running build
>     running build_ext
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\setup.py", line 60, in <module>
>         'Topic :: Text Processing :: Markup :: XML'
>       File "*\testp\lib\site-packages\setuptools\__init__.py", line 143, in setup
>         return distutils.core.setup(**attrs)
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\core.py", line 148, in setup
>         dist.run_commands()
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 966, in run_commands
>         self.run_command(cmd)
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "*\testp\lib\site-packages\setuptools\command\install.py", line 61, in run
>         return orig.install.run(self)
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\command\install.py", line 545, in run
>         self.run_command('build')
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\command\build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "C:\Program Files (x86)\Python37-32\lib\distutils\dist.py", line 985, in run_command
>         cmd_obj.run()
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\setup.py", line 11, in run
>         self.patch_options()
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\setup.py", line 16, in patch_options
>         ext.define_macros.extend(xmlsec_setupinfo.define_macros())
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\xmlsec_setupinfo.py", line 48, in define_macros
>         macros.extend(xmlsec_config()['define_macros'])
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\xmlsec_setupinfo.py", line 111, in xmlsec_config
>         __XMLSEC_CONFIG = load_xmlsec1_config()
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\xmlsec_setupinfo.py", line 158, in load_xmlsec1_config
>         OPTION_DOWNLOAD_DIR, config['include_dirs'], config['library_dirs']
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\xmlsec_extra.py", line 15, in get_prebuilt_libs
>         libs = download_and_extract_windows_binaries(download_dir)
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\xmlsec_extra.py", line 67, in download_and_extract_windows_binaries
>         libs[ln] = unpack_zipfile(destfile, destdir)
>       File "*\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\xmlsec_extra.py", line 94, in unpack_zipfile
>         f = zipfile.ZipFile(zipfn)
>       File "C:\Program Files (x86)\Python37-32\lib\zipfile.py", line 1222, in __init__
>         self._RealGetContents()
>       File "C:\Program Files (x86)\Python37-32\lib\zipfile.py", line 1289, in _RealGetContents
>         raise BadZipFile("File is not a zip file")
>     zipfile.BadZipFile: File is not a zip file
>     Retrieving "https://ci.appveyor.com/api/buildjobs/7k878q7rvogcdyd9/artifacts/libxml2-2.9.4.win32.zip" to "build/extra\libxml2-2.9.4.win32.zip"
>     Unpacking libxml2-2.9.4.win32.zip into build/extra
> 
>     ----------------------------------------
> Command "*\testp\scripts\python.exe -u -c "import setuptools, tokenize;__file__=*\\AppData\\Local\\Temp\\pip-install-jnchsc4g\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\*\AppData\Local\Temp\pip-record-v7t_rx_3\install-record.txt --single-version-externally-managed --compile --install-headers *\testp\include\site\python3.7\xmlsec" failed with error code 1 in *\AppData\Local\Temp\pip-install-jnchsc4g\xmlsec\

**Comment by talebi1** [comment] 2020-01-06 08:49
Duplicate of #98

**Comment by hoefling** [comment] 2020-05-21 00:10
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.

**Closed by hoefling** 2020-05-21 00:10 UTC
