### ISSUE TITLE
I can't install xmlsec on Windows 10

### ISSUE THREAD

**Issue by priyank001** [mehcode/python-xmlsec#88] opened 2018-09-20 12:31 UTC
I am trying to install [_xmlsec_ ](https://pypi.org/project/isodate/) for [Python3-SAML](https://github.com/onelogin/python3-saml) in Windows 10 .
I am using Python3.7.0 
SAML2.4.0

```
> pip install xmlsec
Collecting xmlsec
  Using cached https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz
Requirement already satisfied: pkgconfig in c:\program files (x86)\python37-32\lib\site-packages (from xmlsec) (1.4.0)
Requirement already satisfied: lxml>=3.0 in c:\program files (x86)\python37-32\lib\site-packages (from xmlsec) (4.2.4)
Installing collected packages: xmlsec
  Running setup.py install for xmlsec ... error
    Complete output from command "c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\PRIYAN~1.NAM\\AppData\\Local\\Temp\\pip-install-viofqfv7\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PRIYAN~1.NAM\AppData\Local\Temp\pip-record-d9pyi15h\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    error: HTTP Error 404: The specified blob does not exist.
    Retrieving "https://ci.appveyor.com/api/buildjobs/7k878q7rvogcdyd9/artifacts/libxml2-2.9.4.win32.zip" to "build/extra\libxml2-2.9.4.win32.zip"

    ----------------------------------------
Command ""c:\program files (x86)\python37-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\PRIYAN~1.NAM\\AppData\\Local\\Temp\\pip-install-viofqfv7\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\PRIYAN~1.NAM\AppData\Local\Temp\pip-record-d9pyi15h\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\PRIYAN~1.NAM\AppData\Local\Temp\pip-install-viofqfv7\xmlsec\
```

**Comment by bgaifullin** [comment] 2018-09-21 15:39
There is a problems with pushing new version to pypi, as a workarround you can download latest version from github.  https://github.com/mehcode/python-xmlsec/releases/tag/1.3.5

@mehcode  could you please check: travis fails with error
```
HTTPError: 401 Client Error: This password appears in a breach or has been compromised and cannot be used. See the FAQ entry at https://pypi.org/help/#compromised-password for more information. for url: https://upload.pypi.org/legacy/
```

**Comment by Jyotir-Parmar** [comment] 2018-09-26 05:54
Hi @bgaifullin,

I am also not able to install it on Mac or Centos. This is the error i am getting.

```
Failed building wheel for xmlsec

Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/j8/gzn7zrh52zz52pq1gnc_c4980000gn/T/pip-qr7r5w68-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/j8/gzn7zrh52zz52pq1gnc_c4980000gn/T/pip-6bxlfqza-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/j8/gzn7zrh52zz52pq1gnc_c4980000gn/T/pip-qr7r5w68-build/
```

**Comment by bgaifullin** [comment] 2018-09-28 09:46
@Jyotir-Parmar  can you try to build with vebose mode, to get more information about error.
`pip  -v  install ...`

**Comment by Jyotir-Parmar** [comment] 2018-10-04 13:30
@bgaifullin here is the full error log 

`Collecting xmlsec
  1 location(s) to search for versions of xmlsec:
  * https://pypi.python.org/simple/xmlsec/
  Getting page https://pypi.python.org/simple/xmlsec/
  Looking up "https://pypi.python.org/simple/xmlsec/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/xmlsec/" in the cache
  Current age based on date: 780198
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  Starting new HTTPS connection (1): pypi.org
  "GET /simple/xmlsec/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/xmlsec/
    Found link https://files.pythonhosted.org/packages/33/56/50fca01ea43aaecc2713ca2c7c160456a51b3bad55c77f3427bc9a060283/xmlsec-0.1.0.tar.gz#sha256=d166a70d4ac74a1aa0e7336af431ccee7cc0f3ed63203ff506e0a1440948ce88 (from https://pypi.org/simple/xmlsec/), version: 0.1.0
    Found link https://files.pythonhosted.org/packages/02/51/1d5a86001b638f280870018e7e7544a632c1432d569fd6a5f1ec7fcd08c1/xmlsec-0.1.1.tar.gz#sha256=83e83b97d53d78c94de2c462f8801744d6e0b7f8fc740b469fdf10b2aef8af65 (from https://pypi.org/simple/xmlsec/), version: 0.1.1
    Found link https://files.pythonhosted.org/packages/f1/52/8a1a175b70aa0e73654d3fcf07220a86a09a33eacf56394e1667e98f699b/xmlsec-0.1.2.tar.gz#sha256=233dabf1e1ff504dcdbf91d06025a0711ed8de5fff312d64bc704f7368f3a51b (from https://pypi.org/simple/xmlsec/), version: 0.1.2
    Found link https://files.pythonhosted.org/packages/f6/d2/ccaaf2b1949e18cbebca1db9603ffda97c0fe3c43db236f89abf372f0433/xmlsec-0.2.0.tar.gz#sha256=c5c8531039646045ffe5442b74db028bcd5c9b4249511b0cc1b7eee45c0e1139 (from https://pypi.org/simple/xmlsec/), version: 0.2.0
    Found link https://files.pythonhosted.org/packages/7c/94/a3fedbd0fa66efb6dca82081a02563c12299966b1918295f338fe9a488dc/xmlsec-0.3.0.tar.gz#sha256=2717ef9a2836b6ce719d08b4d5841cedb89af9197238dea87c73c10a295f397c (from https://pypi.org/simple/xmlsec/), version: 0.3.0
    Found link https://files.pythonhosted.org/packages/10/5e/d0918b2de681c14c03d96be57399ab98d45b76a994c77844c67624de9f81/xmlsec-0.3.1.tar.gz#sha256=fd50f38e5c65b5cb70d5faa0b32bf05eb91ab90b77e1bf22926519c1289e4caa (from https://pypi.org/simple/xmlsec/), version: 0.3.1
    Found link https://files.pythonhosted.org/packages/f7/ba/33cc2de8191ccf4ef90fcf7dacf71d66ad70068bc2d2b85915c1062ef138/xmlsec-0.3.3.tar.gz#sha256=f5d86bbe2d55e7bf576bc3a1c2c33068bac0725f23e57650980d451637b2c762 (from https://pypi.org/simple/xmlsec/), version: 0.3.3
    Found link https://files.pythonhosted.org/packages/a3/04/1f183f82e404620cec639219d70052599df01a5209b19ef87b1ec47bbedb/xmlsec-0.4.0.tar.gz#sha256=b3e6150288db6026640f2c6fb05b0ecb536634429becbf36770a5fc5ce7405a3 (from https://pypi.org/simple/xmlsec/), version: 0.4.0
    Found link https://files.pythonhosted.org/packages/87/a0/360030ce8a3629a8073249d255b56c7a455ce00d293eaa06b2206b0e7472/xmlsec-0.5.0.tar.gz#sha256=6269a90ee748229bfe761eb5b5cee0d0ffd4f832c8659d38f298b7c18a15f71d (from https://pypi.org/simple/xmlsec/), version: 0.5.0
    Found link https://files.pythonhosted.org/packages/aa/21/f322ca9ad60e1dcae0041568c2833220a5535e2163a49c5cae46ffdc0bdd/xmlsec-0.6.0.tar.gz#sha256=dc96bdf46c6eb916604c76a121a69beadb9e5729debcb460f097ac2de575f404 (from https://pypi.org/simple/xmlsec/), version: 0.6.0
    Found link https://files.pythonhosted.org/packages/e1/ec/0330f39bc5eb270b6b62a9dbb11194c6d4215b48ef8d04c78a30dc1d2d1d/xmlsec-0.6.1.tar.gz#sha256=1bdb36f0c8e3be0cb980d8eff5c3b1e70ef758b998d07dd8b6cbb8993524b208 (from https://pypi.org/simple/xmlsec/), version: 0.6.1
    Found link https://files.pythonhosted.org/packages/14/18/f1f3980677b6c32c1f0c8b38fbf996c83f7c322c9d04aa34bf91995804d6/xmlsec-1.0.1.tar.gz#sha256=8527975779c8ad1a6347a893b604d6ca7ced1553ece4ebcc9269f6ec8a3aec44 (from https://pypi.org/simple/xmlsec/), version: 1.0.1
    Found link https://files.pythonhosted.org/packages/b5/b3/93249007b5919dfe7d6ba84a3047014675fd7c5fa9417852df1943dc6637/xmlsec-1.0.2.dev0.tar.gz#sha256=754886f02f0d0f9b9ddf3b8f876b122179958614f09503d6002d2f695b20427d (from https://pypi.org/simple/xmlsec/), version: 1.0.2.dev0
    Found link https://files.pythonhosted.org/packages/01/00/c3062ee92e7b1f7a819390a595e78e18d4b28a6381cb055b3fb7eab9e59e/xmlsec-1.0.3.dev0.tar.gz#sha256=9c3983ee1fc82268aec54f44f8125f5c601d88b554e696ae67096e9e0a681cf9 (from https://pypi.org/simple/xmlsec/), version: 1.0.3.dev0
    Found link https://files.pythonhosted.org/packages/ac/a7/07b866172086f40f84c5f9d536db7080d67badb153a43ff1beca1a8f375d/xmlsec-1.0.3.tar.gz#sha256=cf02978c2825479c1bd44a12d6014691501b5db9aa2584dc3e5587f41cba32b9 (from https://pypi.org/simple/xmlsec/), version: 1.0.3
    Found link https://files.pythonhosted.org/packages/65/9e/a64666ca448d4683fb16e4523dce2958f501da16fe18e0be4b739c326794/xmlsec-1.0.4.tar.gz#sha256=95bf36bc9d409dbc5c9600a948f58c1f92de159d6d74795700c36cc9a2fd4e60 (from https://pypi.org/simple/xmlsec/), version: 1.0.4
    Found link https://files.pythonhosted.org/packages/c4/bf/a46e03c277ef42ff3dba791c8f08c16edca4157a31dc971339b1be12b87b/xmlsec-1.0.5.tar.gz#sha256=4230757cb572c444a28b87f66fbcd4d83c0987e5aad4ea2d863f8110513c0fe4 (from https://pypi.org/simple/xmlsec/), version: 1.0.5
    Found link https://files.pythonhosted.org/packages/89/86/90921f9c0b0fe14097f028b70b4c2ba0777c43234772286a6d25224161af/xmlsec-1.0.6.tar.gz#sha256=7628c0c520f39fef5a007f4ecec550dcc9b47522d6cf5aaa699383b9597865f3 (from https://pypi.org/simple/xmlsec/), version: 1.0.6
    Found link https://files.pythonhosted.org/packages/14/65/96dffc4e9a96be55b2c75ad4cb44020a91f5bc8df704f4c40caf181886f7/xmlsec-1.0.7.tar.gz#sha256=0797b0c737ea18574a55e6d36c3504beae20f6acaad71db7bc2e19dd1185cf8a (from https://pypi.org/simple/xmlsec/), version: 1.0.7
    Found link https://files.pythonhosted.org/packages/56/4c/ed4ccd12e6f2fd58e195e7d782c1b165338e36dfb2ef933a02794231686e/xmlsec-1.0.8.tar.gz#sha256=3acd191b9999038e3ab2ce7ee8663b4aa3f49eef251b15e2bf87bf437354a4d4 (from https://pypi.org/simple/xmlsec/), version: 1.0.8
    Found link https://files.pythonhosted.org/packages/ab/b7/db19c5b3231078a5f25d4de346e167ac56e2de862e5fb8159e8969fc3971/xmlsec-1.0.9.tar.gz#sha256=307bb107c359278faa77bf408cff955419d0eb0bf08d11428a333f60d7f46552 (from https://pypi.org/simple/xmlsec/), version: 1.0.9
    Found link https://files.pythonhosted.org/packages/a4/7d/dadea9c3d0c1c8f1f3a0c427f205be29f808a6deda1257281c93ec0af129/xmlsec-1.1.0.tar.gz#sha256=63d1ff6df08d0665be54d4fef19c191d984011c2cb1a32526958684fec38fc9d (from https://pypi.org/simple/xmlsec/), version: 1.1.0
    Found link https://files.pythonhosted.org/packages/c5/12/4eabe5a05804e8883ea9584c546df7c8aab20ee96d50ea55d2a62720151f/xmlsec-1.2.0.tar.gz#sha256=584db09e8e95bd4393b1cd631012f58f66fa2efec5f59ac204019f028cfe2dc3 (from https://pypi.org/simple/xmlsec/), version: 1.2.0
    Found link https://files.pythonhosted.org/packages/b6/ca/d87559f16a4f79870bf006109fa95119e76410e087f32b0e77050ffa2b06/xmlsec-1.3.1.tar.gz#sha256=8fe3877194e1daca83500fa7478bc51e6eb2f93835e2760d2c3fe8aaa1134d84 (from https://pypi.org/simple/xmlsec/), version: 1.3.1
    Found link https://files.pythonhosted.org/packages/57/2e/fd42a79472c19b7c01ead43ab3c2120554234441848ac790f9839993443e/xmlsec-1.3.2.tar.gz#sha256=dd4366f22aa4d99d7a207b7900c82e1fa75f3f93a1562b623300c94dfc129253 (from https://pypi.org/simple/xmlsec/), version: 1.3.2
    Found link https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz#sha256=e573c0172174973223d874ffd158ecd4e0faa761015474385289a6468dd29ed6 (from https://pypi.org/simple/xmlsec/), version: 1.3.3
  Using version 1.3.3 (newest of versions: 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.3.1, 0.3.3, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 1.0.1, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.2.0, 1.3.1, 1.3.2, 1.3.3)
  Looking up "https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz" in the cache
  Current age based on date: 782770
  Freshness lifetime from max-age: 365000000
  The response is "fresh", returning cached response
  365000000 > 782770
  Using cached https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz
  Downloading from URL https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz#sha256=e573c0172174973223d874ffd158ecd4e0faa761015474385289a6468dd29ed6 (from https://pypi.org/simple/xmlsec/)
  Running setup.py (path:/tmp/pip-build-98_8l9kh/xmlsec/setup.py) egg_info for package xmlsec
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/xmlsec.egg-info
    writing pip-egg-info/xmlsec.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/xmlsec.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/xmlsec.egg-info/requires.txt
    writing top-level names to pip-egg-info/xmlsec.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/xmlsec.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/xmlsec.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/xmlsec.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-98_8l9kh/xmlsec has version 1.3.3, which satisfies requirement xmlsec from https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz#sha256=e573c0172174973223d874ffd158ecd4e0faa761015474385289a6468dd29ed6
Requirement already satisfied: pkgconfig in /usr/lib/python3.6/site-packages (from xmlsec)
Requirement already satisfied: lxml>=3.0 in /usr/lib64/python3.6/site-packages (from xmlsec)
Building wheels for collected packages: xmlsec
  Running setup.py bdist_wheel for xmlsec ...   Destination directory: /tmp/tmp7dxu46_spip-wheel-
  Running command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-98_8l9kh/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp7dxu46_spip-wheel- --python-tag cp36
  running bdist_wheel
  running build
  running build_ext
  building 'xmlsec' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/tmp
  creating build/temp.linux-x86_64-3.6/tmp/pip-build-98_8l9kh
  creating build/temp.linux-x86_64-3.6/tmp/pip-build-98_8l9kh/xmlsec
  creating build/temp.linux-x86_64-3.6/tmp/pip-build-98_8l9kh/xmlsec/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.3 -DXMLSEC_CRYPTO="openssl" -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/usr/lib64/python3.6/site-packages/lxml/includes -I/usr/lib64/python3.6/site-packages/lxml -I/usr/lib64/python3.6/site-packages/lxml/includes/libxml -I/usr/lib64/python3.6/site-packages/lxml/includes/libxslt -I/usr/lib64/python3.6/site-packages/lxml/includes/libexslt -I/usr/lib64/python3.6/site-packages/lxml/includes/__pycache__ -I/usr/include/python3.6m -c /tmp/pip-build-98_8l9kh/xmlsec/src/constants.c -o build/temp.linux-x86_64-3.6/tmp/pip-build-98_8l9kh/xmlsec/src/constants.o -g -std=c99 -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
  In file included from /tmp/pip-build-98_8l9kh/xmlsec/src/constants.h:13:0,
                   from /tmp/pip-build-98_8l9kh/xmlsec/src/constants.c:11:
  /tmp/pip-build-98_8l9kh/xmlsec/src/platform.h:16:20: fatal error: Python.h: No such file or directory
   #include <Python.h>
                      ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1
error
  Failed building wheel for xmlsec
  Running setup.py clean for xmlsec
  Running command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-98_8l9kh/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all
  running clean
  removing 'build/temp.linux-x86_64-3.6' (and everything under it)
  'build/lib.linux-x86_64-3.6' does not exist -- can't clean it
  'build/bdist.linux-x86_64' does not exist -- can't clean it
  'build/scripts-3.6' does not exist -- can't clean it
  removing 'build'
Failed to build xmlsec
Installing collected packages: xmlsec
  Running setup.py install for xmlsec ...     Running command /usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-98_8l9kh/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-84h8be1l-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_ext
    building 'xmlsec' extension
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/tmp
    creating build/temp.linux-x86_64-3.6/tmp/pip-build-98_8l9kh
    creating build/temp.linux-x86_64-3.6/tmp/pip-build-98_8l9kh/xmlsec
    creating build/temp.linux-x86_64-3.6/tmp/pip-build-98_8l9kh/xmlsec/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.3 -DXMLSEC_CRYPTO="openssl" -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/usr/lib64/python3.6/site-packages/lxml/includes -I/usr/lib64/python3.6/site-packages/lxml -I/usr/lib64/python3.6/site-packages/lxml/includes/libxml -I/usr/lib64/python3.6/site-packages/lxml/includes/libxslt -I/usr/lib64/python3.6/site-packages/lxml/includes/libexslt -I/usr/lib64/python3.6/site-packages/lxml/includes/__pycache__ -I/usr/include/python3.6m -c /tmp/pip-build-98_8l9kh/xmlsec/src/constants.c -o build/temp.linux-x86_64-3.6/tmp/pip-build-98_8l9kh/xmlsec/src/constants.o -g -std=c99 -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
    In file included from /tmp/pip-build-98_8l9kh/xmlsec/src/constants.h:13:0,
                     from /tmp/pip-build-98_8l9kh/xmlsec/src/constants.c:11:
    /tmp/pip-build-98_8l9kh/xmlsec/src/platform.h:16:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-98_8l9kh/xmlsec
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-98_8l9kh/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-84h8be1l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-98_8l9kh/xmlsec/
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/usr/lib/python3.6/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-98_8l9kh/xmlsec/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-84h8be1l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-98_8l9kh/xmlsec/
Looking up "https://pypi.python.org/pypi/pip/json" in the cache
Returning cached "301 Moved Permanently" response (ignoring date and etag information)
Looking up "https://pypi.org/pypi/pip/json" in the cache
Current age based on date: 782770
Freshness lifetime from max-age: 900
Starting new HTTPS connection (1): pypi.org
"GET /pypi/pip/json HTTP/1.1" 304 0
`

**Comment by bgaifullin** [comment] 2019-01-08 20:35
/tmp/pip-build-98_8l9kh/xmlsec/src/platform.h:16:20: fatal error: Python.h: No such file or directory
#include <Python.h>

the problem is here?

you need to add directory with python header files into headers search path, I am not familiar with windows and do not know how to do this. As alternative you can use pre-built binaries with are attached to repository. https://github.com/mehcode/python-xmlsec/releases/tag/1.3.5

**Comment by srianbury** [comment] 2019-02-04 18:10
Maybe someone with more knowledge about xmlsec can provide more detail about my response but here is what I have found.  @bgaifullin provided .whls above which are for python 2.7 and 3.6 which tells me there's no xmlsec for python 3.7? which the user stated they are using.  I was also using python 3.7 and when after I downloaded the .whl and did pip install <filename>.whl I got something like "this whl is not supported for this platform" meaning not suitable for 3.7, I believe.  I was just starting the project with boilerplate code so I switched to 3.6, downloaded the .whl,  pip installed it and it downloaded.

**Comment by vsingh63** [comment] 2019-02-05 13:44
> Maybe someone with more knowledge about xmlsec can provide more detail about my response but here is what I have found. @bgaifullin provided .whls above which are for python 2.7 and 3.6 which tells me there's no xmlsec for python 3.7? which the user stated they are using. I was also using python 3.7 and when after I downloaded the .whl and did pip install .whl I got something like "this whl is not supported for this platform" meaning not suitable for 3.7, I believe. I was just starting the project with boilerplate code so I switched to 3.6, downloaded the .whl, pip installed it and it downloaded.

yeah. I'm also facing the same issue, available binaries are supported till python 3.6 only.

**Comment by talebi1** [comment] 2020-01-06 08:50
Duplicate of #98

**Comment by hoefling** [comment] 2020-05-21 00:09
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.

**Closed by hoefling** 2020-05-21 00:09 UTC
