### ISSUE TITLE
Tests fails

### ISSUE THREAD

**Issue by peppelinux** [mehcode/python-xmlsec#119] opened 2020-02-09 16:37 UTC
xmlsec version 1.3.3

````
~/DEV3/python-xmlsec$ pytest tests/
================================================================= test session starts =================================================================
platform linux -- Python 3.5.2, pytest-4.0.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/wert/DEV3/python-xmlsec, inifile:
plugins: cov-2.7.1, django-3.4.4, pylama-7.7.1, pythonpath-0.7.3
collected 0 items / 5 errors                                                                                                                          

======================================================================= ERRORS ========================================================================
__________________________________________________________ ERROR collecting tests/test_ds.py __________________________________________________________
tests/test_ds.py:1: in <module>
    from tests import base
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
../Django-Identity.env/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:295: in load_module
    six.exec_(co, mod.__dict__)
tests/base.py:13: in <module>
    ns = {'dsig': xmlsec.constants.DSigNs, 'enc': xmlsec.constants.EncNs}
E   AttributeError: module 'xmlsec.constants' has no attribute 'DSigNs'
_________________________________________________________ ERROR collecting tests/test_enc.py __________________________________________________________
tests/test_enc.py:1: in <module>
    from tests import base
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
../Django-Identity.env/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:295: in load_module
    six.exec_(co, mod.__dict__)
tests/base.py:13: in <module>
    ns = {'dsig': xmlsec.constants.DSigNs, 'enc': xmlsec.constants.EncNs}
E   AttributeError: module 'xmlsec.constants' has no attribute 'DSigNs'
_________________________________________________________ ERROR collecting tests/test_keys.py _________________________________________________________
tests/test_keys.py:1: in <module>
    from tests import base
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
../Django-Identity.env/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:295: in load_module
    six.exec_(co, mod.__dict__)
tests/base.py:13: in <module>
    ns = {'dsig': xmlsec.constants.DSigNs, 'enc': xmlsec.constants.EncNs}
E   AttributeError: module 'xmlsec.constants' has no attribute 'DSigNs'
______________________________________________________ ERROR collecting tests/test_templates.py _______________________________________________________
tests/test_templates.py:1: in <module>
    from tests import base
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
../Django-Identity.env/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:295: in load_module
    six.exec_(co, mod.__dict__)
tests/base.py:13: in <module>
    ns = {'dsig': xmlsec.constants.DSigNs, 'enc': xmlsec.constants.EncNs}
E   AttributeError: module 'xmlsec.constants' has no attribute 'DSigNs'
_________________________________________________________ ERROR collecting tests/test_tree.py _________________________________________________________
tests/test_tree.py:1: in <module>
    from tests import base
<frozen importlib._bootstrap>:969: in _find_and_load
    ???
<frozen importlib._bootstrap>:958: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:664: in _load_unlocked
    ???
<frozen importlib._bootstrap>:634: in _load_backward_compatible
    ???
../Django-Identity.env/lib/python3.5/site-packages/_pytest/assertion/rewrite.py:295: in load_module
    six.exec_(co, mod.__dict__)
tests/base.py:13: in <module>
    ns = {'dsig': xmlsec.constants.DSigNs, 'enc': xmlsec.constants.EncNs}
E   AttributeError: module 'xmlsec.constants' has no attribute 'DSigNs'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================================== 5 error in 0.39 seconds ===============================================================
````

and also documentation examples doesn't work for the same problems.

**Comment by hoefling** [comment] 2020-05-21 14:51
@peppelinux this shoudln't be an issue with the latest 1.3.8 release; can you please confirm?

**Comment by hoefling** [comment] 2020-06-04 13:52
Closed as cannot reproduce this. Feel free to ping me if the issue should be reopened, though.

**Closed by hoefling** 2020-06-04 13:52 UTC
Labels: awaiting-response

**Comment by peppelinux** [comment] 2020-06-04 13:57
sorry for the late, I'm far away from this :(
